# Generated by Django 3.2.9 on 2021-12-12 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability',
        ),
        migrations.AddField(
            model_name='rating',
            name='aggregate_average_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='content_wise',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='content_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='design_wise',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='design_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability_wise',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
